name: Create PR on Release

on:
  release:
    types: [released]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pull.outputs.pr_number }}

    steps:
      - name: Checkout
        id: checkout
        # https://github.com/actions/checkout/releases/tag/v4.1.6
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Create Pull Request
        id: create_pull
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          # Building the PR Data
          pr_data=$(jq -n --arg title "Merge release into master" \
                           --arg head "release" \
                           --arg base "main" \
                           --arg body "Automated PR to merge release branch into main based on release event." \
                           '{title: $title, head: $head, base: $base, body: $body}')
          echo "pr_data: $pr_data"
          
          # Requesting the PR creation
          pr_url="https://api.github.com/repos/${{ github.repository }}/pulls"
          echo "pr_url: $pr_url"
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                           -H "Content-Type: application/json" \
                           -d "$pr_data" \
                           "$pr_url")
          echo "$response" | jq .
  
          # Updating the PR assignee
          pr_number=$(echo "$response" | jq '.number')
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT

      - name: Add Assignee
        id: add_assignee
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          PR_NUMBER: ${{ steps.create_pull.outputs.pr_number }}
        run: |
          # Building the data for Assignee
          assignee_data=$(jq -n --arg assignee "${{ github.actor }}" '{assignees: [ $assignee ] }')

          # URL for Assignee assignment
          assignee_url="https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"

          # Request to add the Assignee
          assignee_response=$(curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$assignee_data" \
            "$assignee_url")

          echo "$assignee_response" | jq .
