name: Create PR on Release

on:
  release:
    types: [released]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pull.outputs.pr_number }}

    steps:
      - name: Checkout
        id: checkout
        # https://github.com/actions/checkout/releases/tag/v4.1.6
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Create Pull Request
        id: create_pull
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          # Authenticate to add cards to a project
          gh auth login --with-token
          gh auth refresh -s project
          
          # Building the PR Data
          PR_DATA=$(gh pr create \
            --title "Merge release into master" \
            --body "Automated PR to merge release branch into main based on release event." \
            --base "main" \
            --head "release" \
            --assignee "@me" \
            --project "@tuliomir's test project")
          echo "PR_DATA: $PR_DATA"
